{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "npiper-rest-reference.serviceAccountName" . }}
  labels:
{{ include "npiper-rest-reference.labels" . | nindent 4 }}
{{- end -}}
